name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      IDENTIFICACAO_ALUNO: anp-aluno-28
      DIRETORIO_WEBAPP: ./SiteContagem
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ${{env.DIRETORIO_WEBAPP}} --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    - name: Logando no Azure para Deployment
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
